import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";

// Posts are generated by the Notion pipeline into content/posts/<category>/<slug>.md.
// The routes use the frontmatter `slug`, not the file path.
const posts = defineCollection({
  loader: glob({ pattern: "**/[^_]*.md", base: "./content/posts" }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    draft: z.boolean().default(false),
    slug: z.string(),
    categories: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    summary: z.string().optional().default(""),
    cover: z.string().optional().default(""),
    canonical: z.string().optional().default(""),
    comments: z.boolean().default(true),
    notion_id: z.string().optional(),
    generated_by: z.string().optional(),
    math: z.boolean().optional(),
  }),
});

// Authored static pages (about, privacy, contact, disclaimer) live in content/pages.
const pages = defineCollection({
  loader: glob({ pattern: "**/[^_]*.md", base: "./content/pages" }),
  schema: z.object({
    title: z.string(),
    date: z.coerce.date().optional(),
    draft: z.boolean().default(false),
    slug: z.string(),
    tags: z.array(z.string()).default([]),
    summary: z.string().optional().default(""),
    comments: z.boolean().default(false),
  }),
});

export const collections = { posts, pages };
